# Application Configuration
spring.application.name=Formation
# Désactiver Config Server (TRÈS IMPORTANT)
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

