server.port=8087
spring.application.name=internship-service
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

# Actuator / Monitoring
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
