apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'eureka'
        static_configs: [{targets: ['eureka:8761']}]
        metrics_path: /actuator/prometheus
      - job_name: 'gateway'
        static_configs: [{targets: ['gateway:9090']}]
        metrics_path: /actuator/prometheus
      - job_name: 'user'
        static_configs: [{targets: ['user:8024']}]
        metrics_path: /actuator/prometheus
      - job_name: 'forum'
        static_configs: [{targets: ['forum:8023']}]
        metrics_path: /actuator/prometheus
      - job_name: 'quiz'
        static_configs: [{targets: ['quiz:8025']}]
        metrics_path: /actuator/prometheus
      - job_name: 'course'
        static_configs: [{targets: ['course:8086']}]
        metrics_path: /actuator/prometheus
      - job_name: 'formation'
        static_configs: [{targets: ['formation:8084']}]
        metrics_path: /actuator/prometheus
      - job_name: 'certificat'
        static_configs: [{targets: ['certificat:8022']}]
        metrics_path: /actuator/prometheus
      - job_name: 'eventgestion'
        static_configs: [{targets: ['eventgestion:8082']}]
        metrics_path: /actuator/prometheus
      - job_name: 'job-offer'
        static_configs: [{targets: ['job-offer:8083']}]
        metrics_path: /actuator/prometheus
      - job_name: 'payment'
        static_configs: [{targets: ['payment:8075']}]
        metrics_path: /actuator/prometheus
      - job_name: 'ticket'
        static_configs: [{targets: ['ticket:8000']}]
        metrics_path: /actuator/prometheus
      - job_name: 'entreprise'
        static_configs: [{targets: ['entreprise:8085']}]
        metrics_path: /actuator/prometheus
      - job_name: 'internship'
        static_configs: [{targets: ['internship:8087']}]
        metrics_path: /actuator/prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
