apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
      - name: ticket
        image: wassimhamouda/ticket:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/pidb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka:8761/eureka/"
        - name: JAVA_TOOL_OPTIONS
          value: "-Dspring.config.import=optional:classpath:/ -Dspring.datasource.url=jdbc:mysql://mysql:3306/pidb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true -Dspring.datasource.username=root -Dspring.datasource.password="
        - name: SERVER_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: ticket
spec:
  selector:
    app: ticket
  ports:
  - port: 8000
    targetPort: 8000
