spring.application.name=certificat

# Config Server (desactive si non utilise)
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

management.endpoints.web.exposure.include=refresh
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_EMAIL_USER:placeholder@gmail.com}
spring.mail.password=${MY_EMAIL_PASS:placeholder_pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true