name: Course CI

on:
  push:
    paths:
      - 'Team_elevate-main */Team_elevate-main/Team_elevate-main/backEnd/microservices/Course/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-microservice-ci.yml
    with:
      service_name: 'Course'
      service_path: 'Team_elevate-main (3)/Team_elevate-main/Team_elevate-main/backEnd/microservices/Course'
