name: EventGestion CI

on:
  push:
    paths:
      - 'Team_elevate-main */Team_elevate-main/Team_elevate-main/backEnd/microservices/eventGestion/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-microservice-ci.yml
    with:
      service_name: 'EventGestion'
      service_path: 'Team_elevate-main (3)/Team_elevate-main/Team_elevate-main/backEnd/microservices/eventGestion'
