name: Frontend CI

on:
  push:
    paths:
      - 'Team_elevate-main ?3?/Team_elevate-main/Team_elevate-main/skillup_front/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Team_elevate-main (3)/Team_elevate-main/Team_elevate-main/skillup_front"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --force

      - name: Build Angular Project
        run: npm run build
